aeroproj/API/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('adddevices',views.addDevices),
]

aeroproj/aeroproj/urls.py
from django.contrib import admin
from django.urls import include, path
websocket_urlpatterns = []

from sockets.routers import websocket_urlpatterns 



urlpatterns = [
    path("", include("aerouser.urls")),
     path("", include("ventilator.urls")),
    path("admin/", admin.site.urls),
    path("", include('API.urls')),
    # path("", include('sockets.routers'))  
    path("", include(websocket_urlpatterns))
]

aeroproj/aerouser/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("login", views.login, name="login"),
    path("signup",views.signup, name="signup" ),
    path("forgot/",views.forgot, name="forgot"),
    path("otp_verification",views.otp, name="otp_verification"),
    path("password_change/<str:token>",views.password_reset, name="password_change"),
    path("logout",views.logout, name="logout"),
    path("user_landing", views.user_landing, name='user_landing'),
    path("user_homepage/<str:serial_number>", views.user_homepage, name='user_homepage'),
    path("device_details", views.device_info, name='device_details'),
    path("patient_details", views.patient_info, name='patient_details'),
    path("monitor", views.monitors, name='monitor'),
]

aeroproj/aerouser/models.py
from django.db import models
from django.utils import timezone

class userdata(models.Model):
    username=models.CharField(max_length=255,null=True)
    email = models.CharField(max_length=255,null=True)
    password = models.CharField(max_length=255,null=True)
    doctor_id = models.AutoField(primary_key=True,unique=True)

class logs(models.Model):
    serial_number = models.CharField(max_length=50, unique=False)
    email= models.CharField(max_length=255,null=True)
    log_in = models.DateTimeField(null=True,blank=True)
    log_out= models.DateTimeField(null=True,blank=True)
    
    
class PasswordResetToken(models.Model):
    email = models.EmailField(max_length=255,null=True)
    token = models.CharField(max_length=100, editable=False) 
    

    def __str__(self):
        return f"Password Reset Token for {self.email}"
 

aeroproj/ventilator/models.py
from django.db import models

class Ventilator(models.Model):
    STATUS_CHOICES = (
        ('allocated', 'Allocated'),
        ('Not allocated', 'Not Allocated'),
    ) 
    battery_no=models.IntegerField(null=True,unique=True)
    battery_mfg_date=models.DateField(null=True,blank=True)
    serial_number = models.CharField(max_length=50, unique=True) 
    model = models.CharField(max_length=100, null=True, blank=True) #device name
    model_no=models.CharField(max_length=100)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Not allocated')
    lot_no=models.IntegerField(null=True,unique=True)
    mfg_date=models.DateField(null=True,blank=True)
    mac=models.CharField(max_length=100,null=True)
    

class device_logs(models.Model):
    log_id = models.AutoField(primary_key=True,unique=True)
    serial_number = models.CharField(max_length=50)
    device_log_in = models.DateTimeField(null=True, blank=True)
    device_log_out = models.DateTimeField(null=True, blank=True)
    assigned_by_doc_id = models.CharField(max_length=255) 
    assigned_to_patient_id = models.CharField(max_length=255)



class mydevices(models.Model):
    email = models.EmailField(max_length=255,null=True)
    serial_number = models.CharField(max_length=50, unique=False)
  
class Patient(models.Model):
    name = models.CharField(max_length=100)
    patient_id = models.AutoField(primary_key=True,unique=True)
    age = models.IntegerField(null= True)
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    ]
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    
    STATUS_CHOICES = [
        ('PASSIVE', 'Passive'),
        ('EMERGENCY', 'Emergency'),
        ('DISCHARGED', 'Discharged'),
    ]
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='PASSIVE')
    doc_id = models.CharField(max_length=255)  # Link to userdata model
    doc_name = models.CharField(max_length=255, null=True)
    device = models.ForeignKey('Ventilator', on_delete=models.SET_NULL, null=True, blank=True)
    height = models.IntegerField(null=False)
    weight = models.IntegerField(null=False)
    blood = models.CharField(max_length=255,null=False)
    ibw = models.IntegerField(null=False)
    itv = models.IntegerField(null=False)
    bmi = models.IntegerField(null=False)
    admitted_date = models.DateTimeField(null=True, blank=True)
    reason = models.CharField(max_length=255,null=False)
    potential = models.CharField(max_length=255,null=False)
    contact = models.IntegerField(null=False)
    room_no= models.CharField(max_length=255,null=False)

aeroproj/aerouser/views.py
from django.contrib.auth.hashers import make_password,check_password
from django.conf import settings
from django.core.mail import send_mail
import random,time
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.shortcuts import get_object_or_404
from .models import userdata, PasswordResetToken,logs
from django.utils import timezone
from ventilator.models import Ventilator,Patient,device_logs
from django.http import HttpResponseServerError
from django.db.models import Max
from django.shortcuts import redirect
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse
from django.shortcuts import render,redirect

# Login
def login(request):
    if request.method == 'POST':
        field1_data = request.POST.get('email')
        field2_data = request.POST.get('password')
        field3_data = request.POST.get('serial_number')

        if not userdata.objects.filter(email__iexact=field1_data).exists():
            error_message = "Email doesn't exist in the database."
            return render(request, "login.html", {'error_message': error_message})

        user = userdata.objects.get(email=field1_data)
        stored_password = user.password
        name1 = user.username

        if not check_password(field2_data, stored_password):
            error_message = "Wrong password"
            return render(request, "login.html", {'error_message': error_message})
        else:
           
            if field3_data:
                if Ventilator.objects.filter(serial_number=field3_data).exists():
                    new_entry = logs(email=field1_data, serial_number=field3_data, log_in=timezone.now())
                    new_entry.save()
                else:
                    field3_data = None  
            request.session['serial_number'] = field3_data
            request.session['email'] = field1_data
            

            if field3_data:
                return render(request, "landing.html", {'error_message': name1, 'error_message1': field3_data})
            else:
                return redirect('user_landing')  
    else:
        return render(request, "login.html")


# Logout
def logout(request):
    field1_data = request.session.get('serial_number')

    if field1_data:
        try:
            user = logs.objects.filter(serial_number=field1_data).latest('id')
            user.log_out = timezone.now()
            user.save()
            del request.session['serial_number']
            return redirect("login")
        except logs.DoesNotExist:
            print("Logs object does not exist or serial number not found.")
            return HttpResponseServerError('Internal Server Error')
    else:
        print("Serial number not found in session.")
        return HttpResponseServerError('Internal Server Error')


# User registration
def signup(request):
    if request.method == 'POST':
        field1_data = request.POST.get('username')
        field2_data = request.POST.get('email')
        field3_data = request.POST.get('password')

        if userdata.objects.filter(email=field2_data).exists():
            error_message = "Email already exists in the database. Log in"
            return render(request, "signup.html", {'error_message': error_message})
        else:
            request.session['username'] = field1_data    #stores data in the session.
            request.session['email'] = field2_data
            request.session['password'] = field3_data
            otp1 = generate_otp()
            request.session['otp'] = otp1
            subject = 'Welcome to Aerobiosys'
            message = f'Hi {field1_data}, thank you for signing up with Aerobiosys.'
            otp_message = f'Your OTP: {otp1}, please do not share.'
            combined_message = f'{message} {otp_message}'
            email_from = settings.EMAIL_HOST_USER
            recipient_list = [field2_data]
            send_mail(subject, combined_message, email_from, recipient_list)
            return render(request, "otp.html")
    else:
        return render(request, "signup.html")

# OTP generator
def generate_otp():
    timestamp = str(int(time.time()))  
    random_number = str(random.randint(1000, 9999))  
    otp = timestamp[-4:] + random_number[-2:]  
    return otp

# OTP
def otp(request):
    error_message = None 
    user_name = request.session.get('username') # used to get the stored data in the session.
    user_email = request.session.get('email')
    user_password = request.session.get('password')
    user_otp = request.session.get('otp')

    if user_email and user_otp:
        if request.method == 'POST':
            entered_otp = request.POST.get('otp')
            try:
                if entered_otp == user_otp:
                    hashed_password = make_password(user_password)
                    max_doctor_id = userdata.objects.aggregate(Max('doctor_id'))['doctor_id__max']
                    if max_doctor_id is None:
                        doctor_id = 1
                    else:
                        doctor_id = max_doctor_id + 1
                    new_entry = userdata(
                        username=user_name,
                        email=user_email, 
                        password=hashed_password,
                        doctor_id=doctor_id
                        )
                    
                    new_entry.save()
                    return redirect("login")
                else:
                    error_message = "Incorrect OTP"
            except userdata.DoesNotExist:
                error_message = "User not found or email not available."
        else:
            return render(request, "otp.html", {'error_message': error_message})
    else:
        error_message = "User email or OTP not available in session."
    
    return render(request, "otp.html", {'error_message': error_message})


#Token generator      
class PasswordResetTokenGeneratorApp(PasswordResetTokenGenerator):
    def _make_hash_value(self, user, timestamp):
        return (
            str(user.pk) + str(timestamp)
        )

password_reset_token = PasswordResetTokenGeneratorApp()


# Forot password
def forgot(request):
    if request.method == 'POST':
        field1_data = request.POST.get('email')
         
        try:
            user = userdata.objects.get(email=field1_data)
        except userdata.DoesNotExist:
            return render(request, 'forgot_password.html', {'error_message': 'User does not exist.'})
        
        token = password_reset_token.make_token(user)
        reset_link = f'http://localhost:8000/password_change/{token}' 

        subject = 'Reset Password'
        message = f'Click the link to reset your password: {reset_link}'
        email_from = settings.EMAIL_HOST_USER
        recipient_list = [field1_data]
        send_mail(subject, message, email_from, recipient_list)
        new_entry = PasswordResetToken(email=field1_data, token=token,)
        new_entry.save()
        return HttpResponse("Reset link sent")
    return render(request, 'forgot_password.html')
 


# Password reset
def password_reset(request, token):
    token_obj = get_object_or_404(PasswordResetToken, token=token)
    email = token_obj.email

    try:
        user = userdata.objects.get(email=email)
    except userdata.DoesNotExist:
        return HttpResponse("User not found")

    if request.method == 'POST':
        new_password = request.POST.get('new_password')
        confirm_new_password = request.POST.get('confirm_new_password')

        if new_password == confirm_new_password:
            hashed_password = make_password(new_password)
            user.password = hashed_password
            user.save()
            token_obj.delete()  
            return HttpResponse("Password has been reset successfully")
        else:
            return render(request, 'reset_password.html', {'error_message': 'Password does not match'})

    return render(request, "reset_password.html")


# if user logins without specifying the serial number
# Web Interface User login
def user_landing(request):
     if request.method == 'GET':
        devices = Ventilator.objects.all()  
        return render(request, "user_landing.html", {'devices':devices })
     else:
        return render(request, "login.html") 
     
# Homepage
def user_homepage(request,serial_number):
    request.session['serial_number3'] = serial_number
    return render(request,"user_homepage.html",{'device':serial_number})


# Device data
def device_info(request):     
    serial_number = request.session.get('serial_number3')
    ventilator = get_object_or_404(Ventilator, serial_number=serial_number)
    return render(request, "device_data.html", {'ventilator': ventilator})

   
# Patient details
def patient_info(request):

    serial_number = request.session.get('serial_number3')
    try:
        devices = device_logs.objects.filter(serial_number=serial_number)

        if not devices.exists():
            return render(request, "patient_data.html", {'error_message': 'No device found for this serial number.'})
        
        patients_with_device = []
        for device in devices:
            number = device.assigned_to_patient_id
            patients = Patient.objects.filter(patient_id=number)
            patients_with_device.extend(patients)

        if not patients_with_device:
            return render(request, "patient_data.html", {'error_message': 'No patient associated with this device.'})

        return render(request, "patient_data.html", {'patients_with_device': patients_with_device})

    except ObjectDoesNotExist:
        return render(request, "patient_data.html", {'error_message': 'Device log not found for this serial number.'})
     


# monitoring section
def monitors(request):
    serial_number = request.session.get('serial_number3')
    try:
        devices = device_logs.objects.filter(serial_number=serial_number)

        if not devices.exists():

aeroproj/aerouser/templates/device_data.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ventilator Data</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f4f4f4;
        }

        h1 {
            text-align: center;
            margin-bottom: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th, td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        th {
            background-color: #f2f2f2;
        }

        .ventilator-data {
            max-width: 800px;
            margin: auto;
        }

        .status-allocated {
            color: green;
            font-weight: bold;
        }

        .status-not-allocated {
            color: red;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <h1>Ventilator Data</h1>
    <div class="ventilator-data">
        <table>
            <thead>
                <tr>
                    <th>Serial Number</th>
                    <th>Model</th>
                    <th>Status</th>
                    <th>Battery Number</th>
                    <th>Battery Manufacturing Date</th>
                    <th>Model Number</th>
                    <th>Lot Number</th>
                    <th>Manufacturing Date</th>
                    <th>MAC Address</th>
                </tr>
            </thead>
            <tbody>
                    <tr>
                        <td>{{ ventilator.serial_number }}</td>
                        <td>{{ ventilator.model }}</td>
                        <td class="{% if ventilator.status == 'allocated' %}status-allocated{% else %}status-not-allocated{% endif %}">
                            {{ ventilator.status }}
                        </td>
                        <td>{{ ventilator.battery_no }}</td>
                        <td>{{ ventilator.battery_mfg_date }}</td>
                        <td>{{ ventilator.model_no }}</td>
                        <td>{{ ventilator.lot_no }}</td>
                        <td>{{ ventilator.mfg_date }}</td>
                        <td>{{ ventilator.mac }}</td>
                    </tr>
                    <tr>
                        <td colspan="9">No data available</td>
                    </tr>
            </tbody>
        </table>
    </div>
</body>
</html>

aeroproj/aerouser/templates/forgot_password.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Forgot Password</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f0f8ff; /* Light blue background color */
      margin: 0;
      padding: 0;
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh; /* Full viewport height */
    }

    h1 {
      color: #333;
    }

    form {
      background-color: #fff;
      padding: 20px;
      border-radius: 8px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      width: 300px;
    }

    label {
      color: #333;
    }

    input[type="email"] {
      width: calc(100% - 22px); /* Adjusted width to account for padding and border */
      padding: 10px;
      margin-bottom: 10px;
      border: 1px solid #ccc;
      border-radius: 4px;
    }

    input[type="submit"] {
      background-color: #007bff; /* Sky blue button color */
      color: #fff; /* White text color */
      padding: 10px 20px;
      border: none;
      border-radius: 4px;
      cursor: pointer;
      transition: background-color 0.3s;
    }

    

    .error-message {
      color: red;
    }
  </style>
</head>
<body>

  <form action="" method="POST">
    <h1>Forgot Password</h1>
    
    {% csrf_token %}

    <label for="email">Enter your email:</label><br>
    <input type="email" id="email" name="email" required><br><br>
    <p class="error-message">{{ error_message }}</p>
    <input type="submit" value="Reset Password">
  </form>

</body>
</html>

aeroproj/aerouser/templates/landing.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Aerobiosys Innovations</title>
    <style>
        body {
            margin: 0;
            font-family: "Helvetica Neue", sans-serif;
            background: #E2E2E2;
        }
        button {
    background-color: #007bff;
    color: #fff;
    border: none;
    padding: 10px 20px;
    border-radius: 5px;
    cursor: pointer;
    font-size: 16px;
    width: 150px;
    transition: background-color 0.3s;
}

button:hover {
    background-color: #0056b3;
}
        .container {
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
            align-items: center;
            padding: 20px;
        }

        .box {
            width: 400px;
            height: 500px;
            margin: 20px;
            background: white;
            border-radius: 20px;
            overflow: hidden;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .box:nth-child(2) {
            background: black;
        }

        .box img {
            width: 328px;
            height: 313px;
            display: block;
            margin: 20px auto; /* Center the image */
            margin-bottom: 100px;
            border-radius: 20px;
        }

        .content {
            padding: 20px;
            text-align: center;
        }
        .content2{
            padding: 20px;
            margin-top: 25px;
            text-align: center;
            display: flex;
            flex-direction: column;
            row-gap: 10px;
        }
        .title {
            font-size: 40px;
            font-weight: 700;
            color: #000;
            margin-bottom: 20px;
            font-family: "Helvetica Neue Light", sans-serif;
        }

        .subtitle {
            font-size: 24px;
            font-weight: 300;
            color: #007BFF;
            margin-bottom: 100px;
        }

        .read-more a {
            text-align: center;
            font-size: 18px;
            font-weight: 700;
            color: rgba(0, 0, 0, 0.53);
            font-family: "Helvetica Neue Light", sans-serif;
            margin-top: auto;
            text-decoration: none;
        }

        .welcome {
            text-align: center;
            color: #696969;
            font-size: 64px;
            font-weight: 300;
            font-family: "Helvetica Neue Light", sans-serif;
            margin: 20px;
        }
        .logout-btn {
            position: absolute;
            top: 20px;
            right: 20px;
            background-color: #ff0000; 
            color: #fff; 
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
            transition: background-color 0.3s;
        }
         
        .logout-btn:hover {
            background-color: #cc0000; 
        }
        .header {
            text-align: center;
            color: #1f1f1f;
            font-size: 36px;
            font-weight: 300;
            margin-top: 20px;
        }

        @media (min-width: 768px) {
            .box {
                width: calc(33.33% - 40px);
            }
        }
    </style>
</head>
<body>

    <a href="http://127.0.0.1:8000/logout"><button class="logout-btn"> Logout</button></a>
    <div class="welcome">
        <span>Welcome to</span>
        <span style="color: #007BFF;">Aerobiosys Innovations</span>
    </div>

    <div class="header">CurrentUser: {{ error_message }}</div>
    <div class="header">Currentdevice: {{ error_message1 }}</div>

    <div class="container">
        <div class="box">
            <div class="content">
            <div class="title">Facilities</div>
        </div>
            <div class="content2">
                <a href="http://127.0.0.1:8000/device_list" class="view-device" style="text-decoration: none;"><button>  View Devices</button></a>
                <a href="http://127.0.0.1:8000/patient_list" class="view-patient" style="text-decoration: none;"><button> View Patients</button></a>
                <a href="http://127.0.0.1:8000/device_logs" class="view-device" style="text-decoration: none;"><button>Device Logs</button></a>
            </div>
        </div>
    </div>
</body>  
</html> 

<!-- 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>List of Devices</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }

        h1 {
            text-align: center;
            margin-top: 20px;
            font-family: "Helvetica Neue Light", sans-serif;
            color: #333;
        }

        .device-list {
            list-style: none;
            padding: 0;
            margin: 20px;
        }

        .device-list-item {
            display: flex; 
            justify-content: space-between; 
            align-items: center; 
            padding: 12px;
            border-bottom: 1px solid #dddddd; 
            background-color: #ffffff;
            margin-bottom: 5px;
            border-radius: 4px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        .device-list-item div {
            flex: 1;
        }

        .allocate-button {
            background-color: #007bff;
            border: none;
            color: white;
            padding: 8px 16px;
            text-align: center;
            text-decoration: none;
            font-size: 14px;
            cursor: pointer;
            border-radius: 4px;
            transition: background-color 0.3s ease-in-out;
        }

        .allocate-button:hover {
            background-color: #45a049;
        }

        p {
            color: #555;
            margin: 5px 0;
        }

        strong {
            font-weight: bold;
        }
    </style>
</head>
<body>
    <h1>List of Devices</h1>
    <ul class="device-list">
        {% for device in device_logs %}
            <li class="device-list-item">
                <div>
                    <strong>Serial number:</strong> {{ device.serial_number }} <br>
                    <strong>Model:</strong> {{ device.model }}<br>
                    <strong>Status:</strong> {{ device.status }}<br>
                    <strong>Location:</strong> {{ device.location }} <br>
                </div>
                {% if device.status != 'Allocated' %}
                    <a href="{% url 'patient' serial_number1=device.serial_number %}" class="allocate-button">Register</a>
                {% else %}
                    <p>This device is already allocated</p>
                    <a href="{% url 'unallocate_device' serial_number2=device.serial_number %}" class="allocate-button">Unallocate</a>
                {% endif %}
            </li>
        {% empty %}
            <li class="device-list-item">No devices found</li>
        {% endfor %}
    </ul>   
</body>
</html> -->

aeroproj/aerouser/templates/monitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Patient Details</title>
    <style>
        
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }

        h1 {
            text-align: center;
            margin-top: 20px;
        }

        .device-list {
            list-style: none;
            padding: 0;
        }

        .device-list-item {
            display: flex; 
            justify-content: space-between; 
            align-items: center; 
            padding: 12px;
            border-bottom: 1px solid #dddddd; 
            background-color: #ffffff;
            margin-bottom: 5px;
            border-radius: 4px;
        }

        .device-list-item div {
            flex: 1;
        }

        .allocate-button {
            background-color: #007bff;
            border: none;
            color: white;
            padding: 8px 16px;
            text-align: center;
            text-decoration: none;
            font-size: 14px;
            cursor: pointer;
            border-radius: 4px;
            transition: background-color 0.3s ease-in-out;
        }

        .allocate-button:hover {
            background-color: #45a049;
        }

        p {
            color: #555;
        }
    </style>
</head>
<body>
    <h1>List of Devices</h1>
    <ul class="device-list">
        {% for patient in patients_with_device %}
            <li class="device-list-item">
                <div>
                    <strong>Patient ID</strong>: {{ patient.patient_id }} <br>
                    <strong>Name</strong>: {{ patient.name }} <br>
                    <strong>Age</strong>: {{ patient.age }} <br>
                    <strong>Gender</strong>: {{ patient.get_gender_display }} <br>
                    <strong>Status</strong>: {{ patient.get_status_display }}
                </div>
                <a href="" class="allocate-button">Monitor</a>
            </li>
        {% empty %}
            <li class="device-list-item">No patients found</li>
        {% endfor %}
    </ul>
</body>
</html>

aeroproj/aerouser/templates/patient_data.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Patient Details</title>
    <style>
        
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f4f4f4;
        }

        h1 {
            text-align: center;
            margin-bottom: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th, td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        th {
            background-color: #f2f2f2;
        }

        .ventilator-data {
            max-width: 800px;
            margin: auto;
        }

        .status-allocated {
            color: green;
            font-weight: bold;
        }

        .status-not-allocated {
            color: red;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <h1>Patient Details</h1>
    {% if error_message %}
        <p>{{ error_message }}</p>
    {% else %}
        <div class="patient-details">
            <table>
                <thead>
                    <tr>
                        <th>Patient ID</th>
                        <th>Name</th>
                        <th>Age</th>
                        <th>Gender</th>
                        <th>Status</th>
                        <th>Doctor ID</th>
                        <th>Doctor Name</th>
                         <th>Height</th>
                        <th>Weight</th>
                        <th>Blood Group</th>
                        <th>ibw</th>
                        <th>itv</th>
                        <th>bmi</th>
                        <th>Admitted_date</th>
                        <th>Reason</th>
                        <th>Potential</th>
                        <th>Contact</th>
                        <th>Room No</th>
                    </tr>
                </thead>
                <tbody>
                    {% for patient in patients_with_device %}
                        <tr>
                            <td>{{ patient.patient_id }}</td>
                            <td>{{ patient.name }}</td>
                            <td>{{ patient.age }}</td>
                            <td>{{ patient.get_gender_display }}</td>
                            <td>{{ patient.get_status_display }}</td>
                            <td>{{ patient.doc_id }}</td>
                            <td>{{ patient.doc_name }}</td>
                            <td>{{ patient.height}}</td>
                            <td>{{ patient.weight}}</td>
                            <td>{{ patient.blood }}</td>
                            <td>{{ patient.ibw}}</td>
                            <td>{{ patient.itv }}</td>
                            <td>{{ patient.bmi }}</td>
                            <td>{{ patient.admitted_date }}</td>
                            <td>{{ patient.reason }}</td>
                            <td>{{ patient.potential }}</td>
                            <td>{{ patient.contact }}</td>
                            <td>{{ patient.room_no }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% endif %}
</body>
</html>